cmake_minimum_required(VERSION 3.18)

if(NOT DEFINED INPUT)
    message(FATAL_ERROR "spirv_to_header.cmake: INPUT is required")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "spirv_to_header.cmake: OUTPUT is required")
endif()
if(NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "spirv_to_header.cmake: VAR_NAME is required")
endif()
if(NOT DEFINED NAMESPACE)
    message(FATAL_ERROR "spirv_to_header.cmake: NAMESPACE is required")
endif()

foreach(_MRUNTIME_VAR IN ITEMS INPUT OUTPUT VAR_NAME NAMESPACE)
    set(_MRUNTIME_VALUE "${${_MRUNTIME_VAR}}")
    if(_MRUNTIME_VALUE MATCHES "^\".*\"$")
        string(REGEX REPLACE "^\"(.*)\"$" "\\1" _MRUNTIME_VALUE "${_MRUNTIME_VALUE}")
        set(${_MRUNTIME_VAR} "${_MRUNTIME_VALUE}")
    endif()
endforeach()

file(READ "${INPUT}" _MRUNTIME_SPIRV_HEX HEX)
string(LENGTH "${_MRUNTIME_SPIRV_HEX}" _MRUNTIME_HEX_LEN)

math(EXPR _MRUNTIME_BYTES "${_MRUNTIME_HEX_LEN} / 2")
math(EXPR _MRUNTIME_REMAINDER "${_MRUNTIME_BYTES} % 4")
if(NOT _MRUNTIME_REMAINDER EQUAL 0)
    message(FATAL_ERROR "spirv_to_header.cmake: SPIR-V size must be a multiple of 4 bytes")
endif()

file(WRITE "${OUTPUT}" "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\nnamespace ${NAMESPACE} {\n\n")
file(APPEND "${OUTPUT}" "alignas(4) static constexpr uint8_t ${VAR_NAME}[] = {\n")

math(EXPR _MRUNTIME_LAST_BYTE "${_MRUNTIME_BYTES} - 1")
set(_MRUNTIME_BYTES_PER_LINE 12)
math(EXPR _MRUNTIME_LAST_COL "${_MRUNTIME_BYTES_PER_LINE} - 1")

foreach(i RANGE 0 "${_MRUNTIME_LAST_BYTE}")
    math(EXPR _MRUNTIME_OFF "${i} * 2")
    string(SUBSTRING "${_MRUNTIME_SPIRV_HEX}" "${_MRUNTIME_OFF}" 2 _MRUNTIME_BYTE_HEX)
    string(TOLOWER "${_MRUNTIME_BYTE_HEX}" _MRUNTIME_BYTE_HEX)

    file(APPEND "${OUTPUT}" "    0x${_MRUNTIME_BYTE_HEX},")
    math(EXPR _MRUNTIME_COL "${i} % ${_MRUNTIME_BYTES_PER_LINE}")
    if(_MRUNTIME_COL EQUAL _MRUNTIME_LAST_COL)
        file(APPEND "${OUTPUT}" "\n")
    endif()
endforeach()

file(APPEND "${OUTPUT}" "\n};\n\n")
file(APPEND "${OUTPUT}" "static constexpr size_t ${VAR_NAME}Size = sizeof(${VAR_NAME});\n\n")
file(APPEND "${OUTPUT}" "}  // namespace ${NAMESPACE}\n")

unset(_MRUNTIME_SPIRV_HEX)
unset(_MRUNTIME_HEX_LEN)
unset(_MRUNTIME_BYTES)
unset(_MRUNTIME_REMAINDER)
unset(_MRUNTIME_LAST_BYTE)
unset(_MRUNTIME_BYTES_PER_LINE)
unset(_MRUNTIME_LAST_COL)
unset(_MRUNTIME_OFF)
unset(_MRUNTIME_BYTE_HEX)
unset(_MRUNTIME_COL)
unset(_MRUNTIME_VAR)
unset(_MRUNTIME_VALUE)
